import { Injectable, Logger } from '@nestjs/common';
import { createReadStream, existsSync } from 'node:fs';
import { readdir } from 'node:fs/promises';
import { join } from 'node:path';
import { Readable } from 'node:stream';
import { HlsManagerService } from './hls-manager.service';

/**
 * HLS Segment Service manages reading and serving HLS segments and playlists.
 *
 * Responsibilities:
 * 1. Read segment files from disk (they're generated by ffmpeg).
 * 2. Generate a current M3U8 playlist based on available segments.
 * 3. Stream segments to clients.
 */
@Injectable()
export class HlsSegmentService {
	private readonly logger = new Logger(HlsSegmentService.name);

	private readonly hlsOutputDir = './hls-temp';

	constructor(private readonly hlsManager: HlsManagerService) {}

	/**
	 * Generate M3U8 playlist for a job.
	 *
	 * The playlist references all available segments and includes metadata
	 * like segment duration and target duration. When the job is completed,
	 * #EXT-X-ENDLIST is appended so the player stops polling.
	 *
	 * @param jobId Job ID
	 * @returns     M3U8 content or null if job not found
	 */
	async generatePlaylist(jobId: string): Promise<string | null> {
		const jobDir = join(this.hlsOutputDir, jobId);

		try {
			const files = await readdir(jobDir);
			const segments = files
				.filter((f) => f.endsWith('.ts'))
				.sort((a, b) => {
					const numA = parseInt(a.match(/\d+/)![0], 10);
					const numB = parseInt(b.match(/\d+/)![0], 10);
					return numA - numB;
				});

			if (segments.length === 0) {
				this.logger.debug(`Playlist for ${jobId}: no segments yet`);
				return this.generateEmptyPlaylist();
			}

			const lines = [
				'#EXTM3U',
				'#EXT-X-VERSION:3',
				'#EXT-X-TARGETDURATION:4',
				'#EXT-X-MEDIA-SEQUENCE:0',
			];

			for (const segment of segments) {
				lines.push('#EXTINF:3.0,');
				lines.push(segment);
			}

			// Add ENDLIST when transcoding is complete so player stops polling
			if (this.hlsManager.isJobCompleted(jobId)) {
				lines.push('#EXT-X-ENDLIST');
			}

			return lines.join('\n') + '\n';
		} catch (error) {
			this.logger.error(`Failed to read playlist for ${jobId}: ${error}`);
			return null;
		}
	}

	/**
	 * Get a readable stream for a specific segment.
	 *
	 * @param jobId       Job ID
	 * @param segmentName Segment file name (e.g., "out-0.ts")
	 * @returns           Readable stream or null if not found
	 */
	async getSegmentStream(jobId: string, segmentName: string): Promise<Readable | null> {
		// Security: reject any path traversal attempts
		if (segmentName.includes('..') || segmentName.includes('/') || segmentName.includes('\\')) {
			this.logger.warn(`Security: rejected segment name with path traversal: ${segmentName}`);
			return null;
		}

		const segmentPath = join(this.hlsOutputDir, jobId, segmentName);

		if (!existsSync(segmentPath)) {
			this.logger.warn(`Segment not found: ${segmentPath}`);
			return null;
		}

		try {
			return createReadStream(segmentPath);
		} catch (error) {
			this.logger.error(`Failed to read segment ${segmentPath}: ${error}`);
			return null;
		}
	}

	/** Generate an empty playlist for jobs that just started prebuffering */
	private generateEmptyPlaylist(): string {
		return (
			[
				'#EXTM3U',
				'#EXT-X-VERSION:3',
				'#EXT-X-TARGETDURATION:4',
				'#EXT-X-MEDIA-SEQUENCE:0',
			].join('\n') + '\n'
		);
	}
}
