import { Injectable, Logger } from '@nestjs/common';
import { createReadStream, existsSync } from 'node:fs';
import { readdir, readFile } from 'node:fs/promises';
import { join } from 'node:path';
import { Readable } from 'node:stream';

/**
 * HLS Segment Service manages reading and serving HLS segments and playlists.
 *
 * Responsibilities:
 * 1. Read segment files from disk (they're generated by ffmpeg).
 * 2. Generate a current M3U8 playlist based on available segments.
 * 3. Stream segments to clients.
 */
@Injectable()
export class HlsSegmentService {
	private readonly logger = new Logger(HlsSegmentService.name);

	private readonly hlsOutputDir = './hls-temp';

	/**
	 * Generate M3U8 playlist for a job.
	 *
	 * The playlist references all available segments and includes metadata
	 * like segment duration and target duration.
	 *
	 * Format:
	 * #EXTM3U
	 * #EXT-X-VERSION:3
	 * #EXT-X-TARGETDURATION:3
	 * #EXT-X-MEDIA-SEQUENCE:0
	 * #EXTINF:3.0,
	 * out-0.ts
	 * #EXTINF:3.0,
	 * out-1.ts
	 * ...
	 *
	 * @param jobId Job ID
	 * @returns     M3U8 content or null if job not found
	 */
	async generatePlaylist(jobId: string): Promise<string | null> {
		const jobDir = join(this.hlsOutputDir, jobId);

		try {
			// List all segment files in the job directory
			const files = await readdir(jobDir);
			const segments = files
				.filter((f) => f.endsWith('.ts'))
				.sort((a, b) => {
					// Sort by segment number: out-0.ts, out-1.ts, ...
					const numA = parseInt(a.match(/\d+/)![0], 10);
					const numB = parseInt(b.match(/\d+/)![0], 10);
					return numA - numB;
				});

			if (segments.length === 0) {
				// Job exists but no segments yet
				this.logger.debug(`Playlist for ${jobId}: no segments yet`);
				return this.generateEmptyPlaylist();
			}

			// Build playlist with all segments
			const lines = [
				'#EXTM3U',
				'#EXT-X-VERSION:3',
				'#EXT-X-TARGETDURATION:4', // 1 second buffer
				`#EXT-X-MEDIA-SEQUENCE:0`,
			];

			for (const segment of segments) {
				lines.push('#EXTINF:3.0,'); // 3-second segment duration
				lines.push(segment);
			}

			// Only add END tag if we know it's complete
			// (Client should check job status to know if it's done)
			// For now, we don't add it so player knows to keep polling

			return lines.join('\n') + '\n';
		} catch (error) {
			this.logger.error(`Failed to read playlist for ${jobId}: ${error}`);
			return null;
		}
	}

	/**
	 * Get a readable stream for a specific segment.
	 *
	 * @param jobId       Job ID
	 * @param segmentName Segment file name (e.g., "out-0.ts")
	 * @returns           Readable stream or null if not found
	 */
	async getSegmentStream(jobId: string, segmentName: string): Promise<Readable | null> {
		const segmentPath = join(this.hlsOutputDir, jobId, segmentName);

		// Security: ensure segmentName doesn't escape the job directory
		if (!segmentPath.startsWith(join(this.hlsOutputDir, jobId))) {
			this.logger.warn(`Security: attempt to access path outside job dir: ${segmentPath}`);
			return null;
		}

		if (!existsSync(segmentPath)) {
			this.logger.warn(`Segment not found: ${segmentPath}`);
			return null;
		}

		try {
			return createReadStream(segmentPath);
		} catch (error) {
			this.logger.error(`Failed to read segment ${segmentPath}: ${error}`);
			return null;
		}
	}

	/**
	 * Generate an empty playlist for jobs that just started prebuffering.
	 */
	private generateEmptyPlaylist(): string {
		return (
			[
				'#EXTM3U',
				'#EXT-X-VERSION:3',
				'#EXT-X-TARGETDURATION:4',
				'#EXT-X-MEDIA-SEQUENCE:0',
				'# Waiting for first segment...',
			].join('\n') + '\n'
		);
	}
}
