import { Controller, Get, Param, Res, UseGuards, NotFoundException } from '@nestjs/common';
import { ApiOkResponse, ApiNotFoundResponse, ApiOperation, ApiTags, ApiUnauthorizedResponse } from '@nestjs/swagger';
import { JwtAuthGuard } from 'src/auth/guard/jwt-auth.guard';
import { ErrorResponseDto } from 'src/common/dto/error-response.dto';
import { HlsManagerService } from './hls-manager.service';
import { HlsSegmentService } from './hls-segment.service';
import type { Response } from 'express';

/**
 * HLS streaming endpoints for live transcoding pipeline.
 *
 * These endpoints serve the HLS playlist (m3u8) and individual segments (ts).
 * The playlist is updated in real-time as ffmpeg generates segments.
 */
@ApiTags('stream/hls')
@Controller('stream/hls')
@UseGuards(JwtAuthGuard)
export class HlsController {
	constructor(
		private readonly hlsManager: HlsManagerService,
		private readonly segments: HlsSegmentService,
	) {}

	/**
	 * Get HLS playlist (m3u8).
	 *
	 * The playlist contains references to segments and is updated in real-time
	 * as ffmpeg generates new segments.
	 *
	 * @param jobId Job ID from HLS job creation
	 * @returns M3U8 playlist content
	 */
	@Get(':jobId/playlist.m3u8')
	@ApiOperation({ summary: 'Get HLS playlist for a transcoding job' })
	@ApiOkResponse({ type: String, description: 'M3U8 playlist content' })
	@ApiNotFoundResponse({ description: 'Job not found', type: ErrorResponseDto })
	@ApiUnauthorizedResponse({ description: 'Authentication required', type: ErrorResponseDto })
	async getPlaylist(@Param('jobId') jobId: string, @Res() res: Response) {
		const playlist = await this.segments.generatePlaylist(jobId);

		if (!playlist) {
			throw new NotFoundException(`Job ${jobId} not found`);
		}

		res.setHeader('Content-Type', 'application/vnd.apple.mpegurl');
		res.setHeader('Cache-Control', 'no-cache, no-store, must-revalidate');
		res.send(playlist);
	}

	/**
	 * Get a specific HLS segment (ts file).
	 *
	 * Segments are generated by ffmpeg and stored on disk.
	 *
	 * @param jobId       Job ID
	 * @param segmentName Name of segment file (e.g., "out-1.ts")
	 * @returns           TS segment data
	 */
	@Get(':jobId/:segmentName')
	@ApiOperation({ summary: 'Get HLS segment file' })
	@ApiOkResponse({ description: 'MPEG-TS segment' })
	@ApiNotFoundResponse({ description: 'Segment not found', type: ErrorResponseDto })
	@ApiUnauthorizedResponse({ description: 'Authentication required', type: ErrorResponseDto })
	async getSegment(
		@Param('jobId') jobId: string,
		@Param('segmentName') segmentName: string,
		@Res() res: Response,
	) {
		const stream = await this.segments.getSegmentStream(jobId, segmentName);

		if (!stream) {
			throw new NotFoundException(`Segment ${segmentName} not found`);
		}

		res.setHeader('Content-Type', 'video/mp2t');
		res.setHeader('Cache-Control', 'public, max-age=3600');
		stream.pipe(res);
	}

	/**
	 * Get job status and progress.
	 *
	 * @param jobId Job ID
	 * @returns     Current status including progress and playlist URL
	 */
	@Get(':jobId/status')
	@ApiOperation({ summary: 'Get HLS job status' })
	@ApiOkResponse({
		schema: {
			type: 'object',
			properties: {
				jobId: { type: 'string' },
				status: { type: 'string', enum: ['prebuffering', 'transcoding', 'completed', 'failed'] },
				progress: { type: 'number', example: 0.75 },
				segmentsAvailable: { type: 'number', example: 25 },
				playlistUrl: { type: 'string', nullable: true },
			},
		},
	})
	@ApiNotFoundResponse({ description: 'Job not found', type: ErrorResponseDto })
	@ApiUnauthorizedResponse({ description: 'Authentication required', type: ErrorResponseDto })
	getStatus(@Param('jobId') jobId: string) {
		const status = this.hlsManager.getJobStatus(jobId);

		if (!status) {
			throw new NotFoundException(`Job ${jobId} not found`);
		}

		return status;
	}
}
